name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package: [WEditor, WEditorHyphen, WEditorBrick]
        ghc: ['8.8.3', '8.6.5', '8.4.4', '8.2.2', '8.0.2', '7.10.3']
        exclude:
          - package: WEditorBrick
            ghc: '8.0.2'
          - package: WEditorBrick
            ghc: '7.10.3'
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{matrix.ghc}}
        cabal-version: '3.0'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      working-directory: cabal/${{matrix.package}}
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      working-directory: cabal/${{matrix.package}}
      run:  cabal build --enable-tests --enable-benchmarks all
    - name: Run test
      working-directory: cabal/${{matrix.package}}
      run: cabal test all
